### PR TITLE
Remove duplicate 317-min-api class

### PR DESCRIPTION
**Pull request by Shadowrs**

### CODE REVIEW

**Comment by JKetelaar** [comment]
Are we sure about this? I remember this was done on purpose, due to a long return value. @SandroCoutinho please check this too.

**Comment by Shadowrs** [comment]
Oh that explains the exception I got earlier. Yeah you're right ... the `getHash()I` call here for debugging is of type `I` .. but the API is `J` for long. Thing is any new content in DClass (debug classes) like the one I did earlier for all objects will have to cascade into all APIs. I added a workaround for this locally, I think it's easier:

317-min-api:

```

                System.out.println(
                        " ID: " + objects[i].getId() +
                                " UID: " + objects[i].resolveHash() +
                                " Location: " + objects[i].getLocation() +
                                " Distance: " + objects[i].distanceTo());

    /**
     * Resolves the hash depending on the API's inner SceneObjectTile getHash() methods' type.
     * @return An object, casted to either Long or Int
     */
    public final Object resolveHash() {
        Object    hash       = (int) 0;
        try {
            RefMethod hashMethod = new RefClass(Context.getInstance().getASMClassLoader().loadClass("org.rev317.min.accessors.SceneObjectTile"), accessor).getMethod("getHash");
            if (hashMethod.getReturnType() == int.class) {
                hash = (int) hashMethod.invoke();
            } else {
                hash = (long) hashMethod.invoke();
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return hash;
    }
```

Code like Scripts built directly on top of DS-API have no issues, this just makes code inside `parabot-client` universal

**Comment by JKetelaar** [comment]
Yet the default API will try to look for the method with return type J, we return I. Don't think we should do this, or should we?

**Comment by Shadowrs** [comment]
default-api code using `resolveHash()` is way better than having to put the 6 `DSceneObject` classes in any api where the hash is a Long instead of Int just to change the type, gonna close this and make a PR for `resolveHash`

Edit: While this is pretty inconsistent since the whole point of custom APIs is to make tiny changes to types and include almost identical classes with these minor changes, this choice was made due to:

- Any DClass (DSceneObject) debugging changes will have to cascade into multiple other APIs
- Reflection involved is low-footprint since it only happens when the user toggles it, rather than being constantly called such as `getBaseX`

**Comment by JKetelaar** [comment]
Really good call 👏

**Pull request closed without merging**
